version: "3.9"

services:
  py-back:
    image: py-back
    build: 
      context: .
      dockerfile: Dockerfile-back
    ports:
      - "3001:3001"
    networks:
      - craftech-net

  node-front:
    image: node-front
    build: 
      context: .
      dockerfile: Dockerfile-front
    ports:
      - "3000:3000"
    networks:
      - craftech-net
    depends_on:
      - py-back

networks:
  craftech-net:
    driver: bridge